broadinstitute/dig-aggregator-methods

bioindex/src/main/resources/annotatedRegions.py, ldsc/src/main/resources/install-ldsc.sh, ldsc/src/main/resources/mergeRegions.pl, ldsc/src/main/resources/partitionRegions.py, ldsc/src/main/scala/LDScoreRegression.scala, ldsc/src/main/scala/PartitionRegionsStage.scala
```
./run.sh ldsc --stage PartitionRegionsStage --reprocess --show-inputs --yes
./run.sh ldsc --stage MergeRegionsStage --reprocess --show-inputs --yes
./run.sh bioindex --stage AnnotatedRegionsStage --reprocess --show-inputs --yes
```
=> Preserving ldsc

bioindex/src/main/resources/annotatedRegions.py, bioindex/src/main/scala/AnnotatedRegionsStage.scala, gregor/src/main/resources/installGREGOR.sh, gregor/src/main/scala/GlobalEnrichmentStage.scala, ldsc/src/main/resources/install-ldsc.sh, ldsc/src/main/resources/mergeRegions.pl, ldsc/src/main/resources/mungeStats.sh, ldsc/src/main/resources/partitionRegions.py, ldsc/src/main/scala/LDScoreRegression.scala, ldsc/src/main/scala/MergeRegionsStage.scala, ldsc/src/main/scala/PartitionRegionsStage.scala
Extra bits to make life easier moving forward with partitioning merging as started by Parul. Mainly it just allows custom partitioning and won't overwrite data, so should make it very easy to test custom partitions as well.
=> [LDSC] Allow for custom partitions in partition/merge staging

bioindex/src/main/resources/geneAssociations.py
Makes MAGMA and 52k versions of the gene-associations / gene-finder bioindices equivalent for future work
=> [Bioindex] Add finder for 52k gene set

vep/src/main/resources/listVariants.py, vep/src/main/scala/ListVariantsStage.scala
List variants stage will now include the LD Server data
=> [VEP] Add LD Server variants to VEP for Burden Binning

bottom-line/src/main/resources/cluster-bootstrap.sh
Installs `fix/sample-overlap` branch from https://github.com/welchr/METAL.git into bottom-line
=> [Bottom Line] Update the metal to the fix branch

ldsc/src/main/resources/install-translate.sh, ldsc/src/main/resources/runGeneticCorrelation.py, ldsc/src/main/resources/translateGeneticCorrelation.py, ldsc/src/main/scala/LDScoreRegression.scala, ldsc/src/main/scala/TranslateGeneticCorrelationStage.scala
Translated and meta-analyzes ancestry-specific data. For mixed datasets, replace with meta-analysis if the stdErr for the meta-analysis is lower than for mixed. Save to individual phenotype-specific files.
=> [LDSC] TranslateGeneticCorrelationStage

bioindex/src/main/resources/geneticCorrelation.py, bioindex/src/main/scala/BioIndex.scala, bioindex/src/main/scala/GeneticCorrelationStage.scala
Add (just mixed) dataset bioindex for genetic correlations. Split out ancestry-specific to separate bit, but still need to set up that bioindex.
=> [Bioindex] GeneticCorrelationStage

magma/README.md, magma/src/main/resources/installMagma.sh, magma/src/main/resources/pathwayAssociations.sh, magma/src/main/resources/pathwayResultsTransform.py, magma/src/main/scala/Magma.scala, magma/src/main/scala/PathwayAssociationsStage.scala, magma/src/main/scala/PathwayResultsTransformStage.scala
Added magma pathway calculations
=> Md magma pathways

magma/src/main/resources/installMagma.sh, magma/src/main/resources/installPythonPackages.sh, magma/src/main/resources/variantAssociations.py, magma/src/main/scala/VariantAssociationsStage.scala
First in a series of three diffs to allow Magma to operate with ancestry-specific data
=> [MAGMA] Variants Associations with ancestry specific

magma/src/main/resources/installMagma.sh, magma/src/main/resources/pathwayAssociations.sh, magma/src/main/scala/PathwayAssociationsStage.scala
Runs against all _SUCCESS but checks for availability of needed file.
=> [Pathways] Ancestry specific version

bioindex/src/main/resources/variantLinks.py, bioindex/src/main/scala/BioIndex.scala, bioindex/src/main/scala/VariantLinksStage.scala
@psmadbec 
New feature
bioindex for S2G data
Testing
`./run.sh bioindex --stage VariantLinksStage --reprocess --show-inputs --yes`
@dkjang new dataset snp2gene
bioindex
{"annotation":"variant_to_gene",
"biosample":"simple tissue",
"biosampleId":"UBERON:0000479",
"biosampleType":"tissue",
"Chromosome":"1",
"dataset":"DSR619JSP",
"End":11008,
"gene":"DDX11L1",
"info":"|Promoter=1",
"method":"combined S2G strategy (cS2G)",
"Score":1,
"Source":"expression QTLs",
"Start":11008,
"State":"variant_to_gene",
"Tissue":"simple_tissue",
"tissueId":"UBERON:0000479",
"variant":"1:11008_C/G" or could be rsid}
=> Snp to gene

bioindex/src/main/resources/credibleSets.py, bioindex/src/main/scala/CredibleSetsStage.scala
This code is effectively dead as the regions source data doesn't exist.
The API will still exist, it just won't be updated. If we want to resurrect then just revert this diff and rebuild from there.
=> [Credible Regions] Remove dead code

ldsc/src/main/resources/mergeRegions.pl, ldsc/src/main/resources/partitionRegions.py
@psmadbec 
New Data Type - candidate regulatory elements
New Feature - bioindex field state indicating original state of an annotation aka Enhancer/Promoter/Other/Accessible Chromatin
Testing
`./run.sh ldsc --stage PartitionRegionsStage --reprocess --show-inputs --yes`
`./run.sh ldsc --stage MergeRegionsStage --reprocess --show-inputs --yes`
`./run.sh bioindex --stage AnnotatedRegionsStage --reprocess --show-inputs --yes`
=> Candidate regulatory elements

bioindex/src/main/resources/geneAssociations.py, config.json
I also checked to see if the security group worked again. It does not. I've removed it as I am pretty confident it doesn't do anything except break everything at this point.
=> [Bioindex] Add chr/start/end to 52k endpoints

basset/.editorconfig, basset/.scalafmt.conf, basset/LICENSE.txt, basset/README.md, basset/built.sbt, basset/project/build.properties, basset/project/plugins.sbt, basset/src/main/resources/bassetBootstrap.sh, basset/src/main/resources/bassetScript.sh, basset/src/main/resources/dcc_basset_lib.py, basset/src/main/resources/fullBassetScript.py, basset/src/main/scala/Basset.scala, basset/src/main/scala/BassetStage.scala, basset/version.sbt
This was removed at one point as it wasn't in production. It will be moved into production soon, so this resurrects the method.
=> [Basset] Initial Resurrection

basset/src/main/resources/bassetBootstrap.sh, basset/src/main/scala/BassetStage.scala
Small diff to change a few imports, get rid of unnecessary comments, and update bootstrap
=> [Basset] Modify to modernize

bioindex/src/main/resources/geneAssociations.py, intake/src/main/resources/geneAssociations.py
The NaN beta was giving some odd data which was breaking the graphQL process. This officially fixes that. Also I added ensemble ID to the dataset and use that in the 600 traits as the join to get the gene position information.
=> Ps remove nan beta 600 trait

intake/src/main/resources/geneAssociations.py
Added a few fields to the gene associations run.
Small bug fix: without `strip()` the last column had a newline escape character
=> [Gene Associations] Add cases and controls

intake/src/main/resources/processor_bootstrap.sh, intake/src/main/resources/variantProcessor.py, intake/src/main/scala/VariantProcessingStage.scala
Plus a few bugs. Likely that one or two more PRs will follow after testing the QC and Scaling jobs as well
=> [Intake] Upgrade SQL Alchemy and EMR image

intake/src/main/resources/variantScaling.py
Part 2. This ended up being a pretty simple one line change since it was already using EMR 6.7.
=> [Intake] Update Scaling SQLAlchemy for version 2

bottom-line/src/main/resources/runAncestrySpecific.sh, bottom-line/src/main/resources/runTransEthnic.sh
Again, almost entirely adding `sudo` to things since I changed the emr instance. Will probably have to do it again for clumping in a few days.
=> [Bottom Line] Fix scripts for upgrading emr instance

bioindex/src/main/resources/huge.py, bioindex/src/main/scala/BioIndex.scala, bioindex/src/main/scala/HugeStage.scala
Combines the common / rare results from Oliver's Huge calculator project. The PR for that should be upcoming.
Rare might not exist (so fill NA with 1.0 as a default for bf_rare and join left). Makes two indices.
=> [Bioindex] Huge bioindex

ldsc/src/main/resources/install-ldscore.sh, ldsc/src/main/resources/regionsToAnnot.py, ldsc/src/main/scala/LDScoreRegression.scala, ldsc/src/main/scala/RegionToAnnotStage.scala
Per annotation runner, computes annotation files for all five ancestries in one job.
~20 minutes per annotation. Doesn't multithread and uses minimal memory so can run 7 at a time on a small m5.2xlarge (online it suggests to leave one CPU open to allow for other tasks). So 21 / hr / box basically (200 annotations should take 5 boxes about 2-3 hours I think).
=> [LDSC] Region to Annot Stage

ldsc/src/main/resources/download-annotation-files.sh, ldsc/src/main/resources/install-gc.sh, ldsc/src/main/resources/install-ldscore.sh, ldsc/src/main/resources/install-sumstats.sh, ldsc/src/main/resources/runPartitionedHeritability.py, ldsc/src/main/scala/LDScoreRegression.scala, ldsc/src/main/scala/PartitionedHeritabilityStage.scala
Runs for phenotype/ancestry. Each takes about 20 minutes, and there are around 1100 I think. So It would take around 20 hours which is comparable with Gregor, but there is lots of room for improvement. Especially as at the moment if you add a single annotation it will run everything again which is a bit impractical. That will have to be fixed (although for now it can be manually bodged a bit)
Uses c5.9xlarge, so a little pricey, but okay. Will need to look into pruning algorithms once we expand to all of the annotations.
=> [LDSC] Partitioned Heritability stage

bioindex/src/main/scala/VariantAssociationsStage.scala, ldsc/src/main/resources/install-sumstats.sh, ldsc/src/main/resources/makeSumstats.py, ldsc/src/main/scala/GeneticCorrelationStage.scala, ldsc/src/main/scala/MakeSumstatsStage.scala, magma/src/main/resources/variantAssociations.py, magma/src/main/scala/VariantAssociationsStage.scala
Some additional changes made during the last release to allow the use of zstd in the bioindex and other services
=> [Aggregator] Additional zstd changes

bioindex/src/main/resources/geneAssociations.py, bioindex/src/main/resources/genes.py, huge/src/main/scala/GeneIdMapStage.scala
I don't know how but this stuff was lost in the shuffle when I landed everything. This is a new diff to reland it
=> [Genes] New diff to fix rebase issue

bioindex/src/main/resources/geneExpression.py
Add in a gene-expression-tissue bioindex
=> [Bioindex] Tissue gene expression

bioindex/src/main/resources/credibleSets.py, bioindex/src/main/scala/CredibleSetsStage.scala
Straightforward: add the two fields.
The job is really small, so also reduce it down to 1 standard box to semi-right size
=> [Credible Sets] Add pmid and method fields to credible sets endpoint

ldsc/src/main/resources/annotToLD.py, ldsc/src/main/resources/regionsToAnnot.py, ldsc/src/main/scala/AnnotToLDStage.scala, ldsc/src/main/scala/MergeRegionsStage.scala, ldsc/src/main/scala/RegionToAnnotStage.scala
Again, gets rid of the concept of manually setting the subregion (annotation, annotation-tissue, etc.) and runs them all since we are going to use them in the next combination step.
=> Annot To LD

ldsc/src/main/resources/annotToLD.py, ldsc/src/main/resources/regionsToAnnot.py, ldsc/src/main/scala/AnnotToLDStage.scala, ldsc/src/main/scala/MergeRegionsStage.scala, ldsc/src/main/scala/RegionToAnnotStage.scala
Converts a region to an annot file. Just used in production so operates as I expect at the moment. Eventually, as part of the grant we just got, I'll be replacing this and the next diff with a very fast run, but for now it will be better to merge this into production to simplify the release a bit.
=> [LDSC] Region to Annot

bioindex/src/main/resources/globalEnrichment.py, ldsc/src/main/resources/combineLD.py, ldsc/src/main/resources/install-translate-ph.sh, ldsc/src/main/resources/translatePartitionedHeritability.py, ldsc/src/main/scala/TranslatePartitionedHeritabilityStage.scala
Some fixes to split out the combined PH data and to create all the bioindices for partitioned heritability
=> [LDSC] Translate and Bioindex PH data

bottom-line/src/main/resources/runMinP.py, bottom-line/src/main/resources/runMinPTransEthnic.py, bottom-line/src/main/scala/BottomLine.scala, bottom-line/src/main/scala/MinPTransEthnicStage.scala
=> [Min P] Trans Ethnic Stage

bottom-line/src/main/resources/naive-bootstrap.sh, bottom-line/src/main/resources/runNaive.py, bottom-line/src/main/resources/runNaiveTransEthnic.py, bottom-line/src/main/scala/BottomLine.scala, bottom-line/src/main/scala/NaiveStage.scala, bottom-line/src/main/scala/NaiveTransEthnicStage.scala
Naive metaanalysis job. Ancestry specific and trans ethnic
=> [Meta] Naive metaanalysis

gene-associations/src/main/resources/combineAssociations.py, gene-associations/src/main/resources/genebassIntake.py, gene-associations/src/main/scala/CombineAssociationsStage.scala, gene-associations/src/main/scala/GeneAssociations.scala, gene-associations/src/main/scala/IntakeGenebassStage.scala
The intake scripts are simple.
The combining bit was slightly altered. Now instead of cauchy p (which we realized wasn't quite correct for the data we were using) we use min p (with an approximation for small pValues). Additionally because of a scaling issue which couldn't be corrected in time, the data is used according to 52K, 600 trait, genebass in that order of priority with no combining.
=> Ps intake genebass

bioindex/src/main/resources/geneExpression.py
This is a small bit that helps prevent strings from getting through to the fontend
=> [Gene Expression] Fix gene expression

bioindex/src/main/scala/AssociationsPlotStage.scala, bioindex/src/main/scala/BioIndex.scala
I finally found this. It took me a while. This splits associations from plotting associations which will help with situations where we don't care about the plot (which can take a long time) which isn't that uncommon of a situation. Also it allows for checking things without having to rerun things unnecessarily.
=> [Bioindex] Split Associations from Plot

bioindex/src/main/scala/TranscriptionsStage.scala, ldsc/src/main/resources/install-translate.sh, ldsc/src/main/scala/TranslateGeneticCorrelationStage.scala, magma/src/main/resources/installTransformPackages.sh, magma/src/main/scala/GeneResultsTransformStage.scala, magma/src/main/scala/PathwayResultsTransformStage.scala
These are mostly moving things to the more up to date EMR. Some of this ended up in another branch but it'll smooth out eventually.
=> [Release] Some release extras which I forgot about

bioindex/src/main/scala/AssociationsPlotStage.scala, gene-associations/src/main/scala/IntakeGenebassStage.scala, ldsc/src/main/scala/CombineLDStage.scala, ldsc/src/main/scala/TranslateGeneticCorrelationStage.scala, magma/src/main/scala/GeneResultsTransformStage.scala, magma/src/main/scala/PathwayResultsTransformStage.scala
I didn't do a good job pulling changes to master prior to my other change it looks like.
=> [Clean up] Left over 6.7.0 EMR specifications

magma/src/main/resources/installMagma.sh, magma/src/main/scala/GeneAssociationsStage.scala, magma/src/main/scala/PathwayAssociationsStage.scala
Without the proper chmod it turned out that magma was just not running, but it was eating the error, so I didn't notice it. Fixes it and I'm rerunning now.
=> [Magma] Silent error for chmod on magma files

bottom-line/src/main/resources/runPlink.py, bottom-line/src/main/scala/BottomLine.scala, bottom-line/src/main/scala/ClumpedPlinkStage.scala
=> [Clump] Speed and add new data

credible-sets/.editorconfig, credible-sets/.scalafmt.conf, credible-sets/LICENSE.txt, credible-sets/README.md, credible-sets/built.sbt, credible-sets/project/build.properties, credible-sets/project/plugins.sbt, credible-sets/src/main/resources/C2CT.py, credible-sets/src/main/resources/bootstrap.sh, credible-sets/src/main/resources/credibleSets.py, credible-sets/src/main/resources/download-cmdga.sh, credible-sets/src/main/resources/mergeSets.py, credible-sets/src/main/scala/C2CTStage.scala, credible-sets/src/main/scala/CredibleSets.scala, credible-sets/src/main/scala/CredibleSetsStage.scala, credible-sets/src/main/scala/MergeSetsStage.scala, credible-sets/version.sbt
A project which takes in both credible sets and clumps and forms a common format for those files. It then merges then (via a simple append). Then an initial c2ct as well, although this will be modified in the future as it is not final in this form.
=> [Credible Sets] Intake, merge, c2ct

ldsc/src/main/resources/install-ldscore.sh, ldsc/src/main/resources/runPartitionedHeritability.py, ldsc/src/main/resources/translatePartitionedHeritability.py, ldsc/src/main/scala/PartitionedHeritabilityStage.scala
=> [LDSC] reapply xtx speed up for tissue specific runs

ldsc/src/main/resources/install-sumstats.sh, magma/src/main/resources/assignGenes.sh, magma/src/main/resources/gatherVariants.py, magma/src/main/resources/geneAssociations.sh, magma/src/main/resources/geneResultsTransform.py, magma/src/main/resources/installMagma.sh, magma/src/main/resources/installTransformPackages.sh, magma/src/main/resources/pathwayAssociations.sh, magma/src/main/resources/pathwayResultsTransform.py, magma/src/main/resources/variantAssociations.py, magma/src/main/scala/AssignGenesStage.scala, magma/src/main/scala/GatherVariantsStage.scala, magma/src/main/scala/VariantAssociationsStage.scala
Uses envvars for magma (and swaps snp out for ldsc as well)
=> [Magma] Use envvars

intake/src/main/resources/variantProcessor.py, intake/src/main/resources/variantScaling.py
Region got refactored out at one point and on occasion causes issues (although only in scaling which is confusing)
=> [Intake] Small fixes

bioindex/src/main/resources/c2ct.py, bioindex/src/main/scala/GeneVariantsStage.scala, bioindex/src/main/scala/TranscriptionsStage.scala, gene-associations/src/main/scala/Intake600TraitStage.scala, huge/src/main/scala/NearestGeneStage.scala, ldsc/src/main/scala/LDScoreRegression.scala
Some small bits and bobs from the June 2024 release
=> [Release] Small fixes

bioindex/src/main/resources/credibleSets.py, bioindex/src/main/scala/CredibleSetsStage.scala, credible-sets/src/main/resources/C2CT.py, credible-sets/src/main/resources/credibleSets.py, credible-sets/src/main/resources/specificity.py
Adjusting C2CT to fix flakiness and remove adjusted data
=> [Credible Sets] New C2CT plus bioindex changes

bioindex/src/main/resources/geneExpression.py
Simple TStat, although Spark is quite bad for this and we should reimplement with a simpler model when possible.
=> [Gene Expression] Q specificity calculation

ldsc/src/main/resources/makeSumstats.py
There were some issues surrounding getting the largest data due to new datasets with only X chromosome, this fixes that by running down the list of mixed datastes and picking the first out that will succeed.
=> [LDSC] Fix for portal DB uncertainty

bottom-line/src/main/resources/clumpedAssociations.py, bottom-line/src/main/resources/mergeClumps.py, bottom-line/src/main/resources/runPlink.py, bottom-line/src/main/scala/BottomLine.scala, bottom-line/src/main/scala/ClumpedAssociationsStage.scala, bottom-line/src/main/scala/ClumpedMergeStage.scala, bottom-line/src/main/scala/ClumpedPlinkStage.scala
Big change to use different clumping params and then merge them for downstream processes like c2ct
=> [Clumping] Use analysis everywhere and merge for downstream processes

bottom-line/src/main/resources/runLargest.py
Previously this method relied on the db and s3 matching in determining which dataset is the largest. That's dangerous. So this instead picks up the largest GWAS dataset that also had been partitioned.
=> [Largest] Take largest available

bioindex/src/main/resources/c2ct.py, bioindex/src/main/scala/C2CTStage.scala, credible-sets/src/main/resources/C2CT.py, credible-sets/src/main/resources/specificity.py, credible-sets/src/main/scala/SpecificityStage.scala
Adds more columns and allows for progressive drilling down into c2ct endpoints
=> [Specificity] Update specificity for changes to Giant

bioindex/src/main/resources/annotatedRegions.py, bioindex/src/main/resources/associations.py, bioindex/src/main/resources/clumpedAssociationsMatrix.py, bioindex/src/main/resources/clumpedVariants.py, bioindex/src/main/resources/credibleSets.py, bioindex/src/main/resources/geneAssociations.py, bioindex/src/main/resources/geneticCorrelation.py, bioindex/src/main/resources/pathwayAssociations.py, bioindex/src/main/resources/phewasAssociations.py, bioindex/src/main/resources/tissueRegions.py, bioindex/src/main/resources/topAssociations.py, ldsc/src/main/resources/translatePartitionedHeritability.py
Will require quite a bit of frontend changes to allow this to work, but this is the time to do it.
=> [Bioindex] Harmonize tissue and ancestry information

bioindex/src/main/resources/singleCell.py, bioindex/src/main/resources/singleCellMetadata.py, bioindex/src/main/scala/BioIndex.scala, bioindex/src/main/scala/SingleCellMetadataStage.scala, bioindex/src/main/scala/SingleCellStage.scala
=> [Single Cell] Metadata

bottom-line/src/main/resources/runLargest.py, bottom-line/src/main/scala/LargestStage.scala
I dropped the transethnic version of the bottom-line analysis sometime in the fall
=> Fix largest

bioindex/src/main/resources/associations.py, bioindex/src/main/resources/clumpedAssociationsMatrix.py, bioindex/src/main/resources/clumpedVariants.py, bioindex/src/main/resources/datasetAssociations.py, bioindex/src/main/resources/geneVariants.py, bioindex/src/main/resources/topAssociations.py, bioindex/src/main/resources/transcriptConsequences.py, bioindex/src/main/resources/variants.py, bioindex/src/main/scala/TranscriptionsStage.scala, bioindex/src/main/scala/VariantsStage.scala, burden-binning/src/main/resources/binning.py, burden-binning/src/main/scala/BurdenBinningStage.scala, huge/src/main/resources/huge-cache.py, huge/src/main/resources/nearest-gene.py, huge/src/main/scala/HugeCacheStage.scala, huge/src/main/scala/NearestGeneStage.scala, magma/src/main/resources/gatherVariants.py, magma/src/main/scala/GatherVariantsStage.scala, vep/src/main/resources/common.py, vep/src/main/resources/cqs.py, vep/src/main/resources/listVariants.py, vep/src/main/resources/runCQSVep.sh, vep/src/main/resources/runCommonVep.sh, vep/src/main/resources/zstd-bootstrap.sh, vep/src/main/scala/CQSVepStage.scala, vep/src/main/scala/CommonStage.scala, vep/src/main/scala/CommonVepStage.scala, vep/src/main/scala/CqsStage.scala, vep/src/main/scala/ListVariantsStage.scala
Splits vep so larger sets on small private repos don't have to also be run, but variant_counts can be run.
=> [VEP] Split VEP

bottom-line/src/main/resources/runNaiveTransEthnic.py, ldsc/src/main/resources/install-ldscore.sh
- **pin ld score**
- **committing what I should have previously!**
=> Naive None Filter
